In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [12]:
#Read the adj matrix into a dataframe
df = pd.read_csv(r"C:\Users\praje\OneDrive\Documents\IGL DEEP STRUCTURES\PrevRefMatrices\common_references_.csv")

In [13]:
df.head()

,Unnamed: 0,Kevin Ford,Jeremy Tyson,Anil Hirani,Sheldon Katz H.,Pierre Albin,Nathan M. Dunfield,Alexandr Kostochka,Rinat Kedem,Renming Song,...,Timur Oikhberg,Felix Leditzky,Kay Kirkpatrick,Xiaochen Jing,Nikolaos Tzirakis,Ely Kerman,Philippe Di Francesco,Richard S. Laugesen,Jeremiah Heller,Rosemary Guzman
0,Kevin Ford,449.0,3.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,Jeremy Tyson,3.0,506.0,1.0,0.0,3.0,1.0,0.0,0.0,9.0,...,2.0,0.0,0.0,0.0,1.0,1.0,0.0,6.0,0.0,1.0
2,Anil Hirani,0.0,1.0,128.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,Sheldon Katz H.,0.0,0.0,0.0,423.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
4,Pierre Albin,0.0,3.0,1.0,0.0,433.0,8.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0

In [14]:
#names of each professor
cols = df.columns

for i in range(len(cols)):
    #skip the first part of row which just has the professor's name
    if i == 0:
        continue

    #Apply the inverse operation which should make bigger similarities have closer distances
    df[cols[i]] = df[cols[i]].map(lambda x: 1 / (x + 1))

In [15]:
df.head()

,Unnamed: 0,Kevin Ford,Jeremy Tyson,Anil Hirani,Sheldon Katz H.,Pierre Albin,Nathan M. Dunfield,Alexandr Kostochka,Rinat Kedem,Renming Song,...,Timur Oikhberg,Felix Leditzky,Kay Kirkpatrick,Xiaochen Jing,Nikolaos Tzirakis,Ely Kerman,Philippe Di Francesco,Richard S. Laugesen,Jeremiah Heller,Rosemary Guzman
0,Kevin Ford,0.002222,0.250000,1.000000,1.000000,1.000000,1.000000,0.166667,1.0,0.333333,...,0.500000,1.0,1.0,1.0,0.5,0.5,1.000000,1.000000,1.0,1.0
1,Jeremy Tyson,0.250000,0.001972,0.500000,1.000000,0.250000,0.500000,1.000000,1.0,0.100000,...,0.333333,1.0,1.0,1.0,0.5,0.5,1.000000,0.142857,1.0,0.5
2,Anil Hirani,1.000000,0.500000,0.007752,1.000000,0.500000,0.500000,1.000000,1.0,1.000000,...,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,0.500000,1.0,1.0
3,Sheldon Katz H.,1.000000,1.000000,1.000000,0.002358,1.000000,0.500000,1.000000,0.5,1.000000,...,1.000000,1.0,1.0,1.0,1.0,1.0,0.333333,1.000000,1.0,1.0
4,Pierre Albin,1.000000,0.250000,0.500000,1.000000,0.002304,0.111111,1.000000,1.0,0.500000,...,1.000000,1.0,0.5,1.0,1.0,0.5,1.000000,0.333333,1.0,1.0

In [16]:
df.to_csv(r"C:\Users\praje\OneDrive\Documents\IGL DEEP STRUCTURES\PrevRefMatrices\dist_ref_prev_inv.csv")

In [17]:
df_2 = pd.read_csv(r"C:\Users\praje\OneDrive\Documents\IGL DEEP STRUCTURES\PrevRefMatrices\common_references_.csv")

df_2.index

df_2.head()

,Unnamed: 0,Kevin Ford,Jeremy Tyson,Anil Hirani,Sheldon Katz H.,Pierre Albin,Nathan M. Dunfield,Alexandr Kostochka,Rinat Kedem,Renming Song,...,Timur Oikhberg,Felix Leditzky,Kay Kirkpatrick,Xiaochen Jing,Nikolaos Tzirakis,Ely Kerman,Philippe Di Francesco,Richard S. Laugesen,Jeremiah Heller,Rosemary Guzman
0,Kevin Ford,449.0,3.0,0.0,0.0,0.0,0.0,5.0,0.0,2.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,Jeremy Tyson,3.0,506.0,1.0,0.0,3.0,1.0,0.0,0.0,9.0,...,2.0,0.0,0.0,0.0,1.0,1.0,0.0,6.0,0.0,1.0
2,Anil Hirani,0.0,1.0,128.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,Sheldon Katz H.,0.0,0.0,0.0,423.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
4,Pierre Albin,0.0,3.0,1.0,0.0,433.0,8.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0

In [18]:
#Make a matrix with the map [sqrt(prof A)sqrt(prof B)] / (Prof A and B + 1)


cols_2 = df_2.columns
rows = df_2.index

for i in range(len(rows)):
    for j in range(len(cols_2)):
        if j == 0:
            continue

        A = np.sqrt(df_2.iloc[i, i+1])
        B = np.sqrt(df_2.iloc[j -1, j])

        C = df_2.iloc[i, j] + 1

        prof = cols_2[j]
        df_2.at[i, prof] = (A + B) / C

In [20]:
df_2.head()
df_2.to_csv(r"C:\Users\praje\OneDrive\Documents\IGL DEEP STRUCTURES\PrevRefMatrices\dist_prev_sqrt.csv")

In [10]:
df_2.head()

,Unnamed: 0,Kevin Ford,Jeremy Tyson,Anil Hirani,Sheldon Katz H.,Pierre Albin,Nathan M. Dunfield,Alexandr Kostochka,Rinat Kedem,Renming Song,...,Timur Oikhberg,Felix Leditzky,Kay Kirkpatrick,Xiaochen Jing,Nikolaos Tzirakis,Ely Kerman,Philippe Di Francesco,Richard S. Laugesen,Jeremiah Heller,Rosemary Guzman
0,Kevin Ford,0.337915,1.370071,1.871791,1.395619,1.646735,1.440987,1.624346,2.022703,1.686430,...,2.688568,3.409732,4.322962,1.995519,2.526720,1.613528,2.290652,3.206128,1.395619,0.581305
1,Jeremy Tyson,1.370071,0.391918,3.788311,2.115793,0.996987,2.183846,6.542114,2.045068,1.358090,...,1.355466,3.454461,2.183846,2.040247,1.019634,3.271785,2.313017,2.152329,4.231585,0.626034
2,Anil Hirani,1.871791,3.788311,0.574960,4.363812,5.117160,1.499973,3.337170,4.222363,6.922675,...,5.554092,1.793344,4.499918,2.172474,5.230397,3.404012,4.758261,6.589213,4.363812,0.758261
3,Sheldon Katz H.,1.395619,2.115793,4.363812,0.515079,2.538294,2.229674,6.633770,1.393930,3.441052,...,2.756761,1.773058,2.229674,2.131903,1.729942,3.363441,1.572563,3.274321,2.161621,0.717690
4,Pierre Albin,1.646735,0.996987,5.117160,2.538294,0.435890,4.401877,6.576299,2.062161,3.412317,...,2.728026,3.488647,1.467292,2.074433,1.026471,3.305971,2.330110,1.622793,2.132885,0.660220

In [ ]:
#create the heatmap

#First need data for within heatmap
#data =